name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Verify uv version
        run: uv --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build the package
        run: uv build

      - name: Publish to PyPI
        run: >
          uv publish
          --username __token__
          --password ${{ secrets.PYPI_API_TOKEN }}
